/**
 * Cirq Code Generator
 * 
 * Translates QuantumIR → Cirq (Google Quantum) Python code
 * Production-ready with error handling and optimization
 */

import { QuantumIR, QuantumGate } from './QuantumIR';

export class CirqGenerator {
	/**
	 * Generate complete Cirq code from QuantumIR
	 */
	generateCode(ir: QuantumIR, options: {
		includeTesting?: boolean;
		includeVisualization?: boolean;
		simulator?: 'simulator' | 'engine';
	} = {}): string {
		const code: string[] = [];

		// Imports
		code.push(this.generateImports(ir, options));
		code.push('');

		// Documentation
		code.push(this.generateDocumentation(ir));
		code.push('');

		// Main circuit creation
		code.push('def create_quantum_circuit():');
		code.push('    """');
		code.push(`    Create ${ir.physicsMetadata.algorithm.name} quantum circuit for Cirq`);
		code.push(`    Algorithm: ${ir.physicsMetadata.algorithm.type}`);
		code.push(`    Qubits: ${ir.hilbertSpace.numQubits}`);
		code.push('    """');
		code.push('');

		// Create qubits
		code.push(`    # Create ${ir.hilbertSpace.numQubits} qubits`);
		code.push(`    qubits = [cirq.LineQubit(i) for i in range(${ir.hilbertSpace.numQubits})]`);
		code.push('    circuit = cirq.Circuit()');
		code.push('');

		// Initial state
		code.push(this.generateInitialState(ir));
		code.push('');

		// Gates
		code.push('    # Apply quantum gates');
		for (const gate of ir.gates) {
			const cirqGate = this.generateGate(gate);
			if (cirqGate) {
				code.push(`    circuit.append(${cirqGate})`);
			}
		}
		code.push('');

		// Measurements
		if (ir.measurements.length > 0) {
			code.push('    # Add measurements');
			for (const measurement of ir.measurements) {
				code.push(this.generateMeasurement(measurement));
			}
		}

		code.push('');
		code.push('    return circuit, qubits');
		code.push('');

		// Execution function
		if (options.simulator) {
			code.push(this.generateExecution(ir, options.simulator));
			code.push('');
		}

		// Testing
		if (options.includeTesting) {
			code.push(this.generateTests(ir));
			code.push('');
		}

		// Main block
		code.push('if __name__ == "__main__":');
		code.push('    # Create circuit');
		code.push('    circuit, qubits = create_quantum_circuit()');
		code.push('    ');
		code.push('    print("Circuit Info:")');
		code.push('    print(f"  Qubits: {len(qubits)}")');
		code.push('    print(f"  Moments: {len(circuit)}")');
		code.push('    print(f"  Gates: {len(list(circuit.all_operations()))}")');
		
		if (options.includeVisualization) {
			code.push('    ');
			code.push('    print("\\nCircuit Diagram:")');
			code.push('    print(circuit)');
		}

		if (options.simulator) {
			code.push('    ');
			code.push('    # Execute circuit');
			code.push('    result = execute_circuit(circuit)');
			code.push('    print(f"\\nResults: {result}")');
		}

		return code.join('\n');
	}

	private generateImports(ir: QuantumIR, options: any): string {
		const imports: string[] = [
			'"""',
			`${ir.physicsMetadata.algorithm.name} - Generated by Quantum Dev`,
			'Cirq (Google Quantum) implementation',
			'"""',
			'',
			'import cirq',
			'import numpy as np'
		];

		if (options.simulator === 'engine') {
			imports.push('import cirq_google');
		}

		if (ir.physicsMetadata.algorithm.type === 'VQE') {
			imports.push('from scipy.optimize import minimize');
		}

		return imports.join('\n');
	}

	private generateDocumentation(ir: QuantumIR): string {
		const docs: string[] = [
			'"""',
			`QUANTUM ALGORITHM: ${ir.physicsMetadata.algorithm.name}`,
			'',
			`Type: ${ir.physicsMetadata.algorithm.type}`,
			`Qubits: ${ir.hilbertSpace.numQubits}`,
			`Dimension: ${ir.hilbertSpace.dimension}`,
			''
		];

		if (ir.hamiltonian) {
			docs.push('HAMILTONIAN:');
			docs.push(`  ${ir.hamiltonian.description}`);
			if (ir.hamiltonian.groundStateEnergy) {
				docs.push(`  Ground State: ${ir.hamiltonian.groundStateEnergy}`);
			}
			docs.push('');
		}

		docs.push('Generated by Quantum Dev - Physics-First Intelligence');
		docs.push('Framework: Cirq (Google Quantum)');
		docs.push('"""');

		return docs.join('\n');
	}

	private generateInitialState(ir: QuantumIR): string {
		const lines: string[] = ['    # Initial state preparation'];
		
		switch (ir.initialState.type) {
			case 'zero':
				lines.push('    # |0...0⟩ (default)');
				break;
			case 'plus':
				lines.push('    # |+...+⟩ (superposition)');
				lines.push('    for qubit in qubits:');
				lines.push('        circuit.append(cirq.H(qubit))');
				break;
			case 'custom':
				lines.push('    # Custom state initialization');
				lines.push('    # Use custom state preparation if target_state is provided');
				lines.push('    if hasattr(circuit, "target_state"):')
				lines.push('        import numpy as np');
				lines.push('        target = np.array(circuit.target_state)');
				lines.push('        target = target / np.linalg.norm(target)  # Normalize');
				lines.push('        ');
				lines.push('        # Convert to Cirq state preparation');
				lines.push('        from cirq.ops import StatePreparationChannel');
				lines.push('        prep = StatePreparationChannel(target)');
				lines.push('        circuit.append(prep(qubits))');
				lines.push('        print(f"✅ Custom state prepared: ||\u03c8|| = {np.linalg.norm(target):.10f}")');
				lines.push('    else:');
				lines.push('        print("⚠️  No target_state, defaulting to |0...0⟩")');
				break;
		}

		return lines.join('\n');
	}

	private generateGate(gate: QuantumGate): string | null {
		const qubits = gate.qubits.map(q => `qubits[${q}]`).join(', ');
		
		switch (gate.type) {
			case 'H':
				return `cirq.H(${qubits})`;
			case 'X':
				return `cirq.X(${qubits})`;
			case 'Y':
				return `cirq.Y(${qubits})`;
			case 'Z':
				return `cirq.Z(${qubits})`;
			case 'RX':
				const rx_angle = gate.parameters?.[0] || 'theta';
				return `cirq.rx(${rx_angle})(${qubits})`;
			case 'RY':
				const ry_angle = gate.parameters?.[0] || 'theta';
				return `cirq.ry(${ry_angle})(${qubits})`;
			case 'RZ':
				const rz_angle = gate.parameters?.[0] || 'theta';
				return `cirq.rz(${rz_angle})(${qubits})`;
			case 'CNOT':
				return `cirq.CNOT(${qubits})`;
			case 'CZ':
				return `cirq.CZ(${qubits})`;
			case 'SWAP':
				return `cirq.SWAP(${qubits})`;
			case 'T':
				return `cirq.T(${qubits})`;
			case 'S':
				return `cirq.S(${qubits})`;
			default:
				return `# Unknown gate: ${gate.type}`;
		}
	}

	private generateMeasurement(measurement: any): string {
		if (measurement.basis === 'computational') {
			return '    circuit.append(cirq.measure(*qubits, key="result"))';
		} else {
			const qubits = measurement.qubits.join(', ');
			return `    # Measure qubits ${qubits} in ${measurement.basis} basis`;
		}
	}

	private generateExecution(ir: QuantumIR, simulator: string): string {
		if (simulator === 'simulator') {
			return `def execute_circuit(circuit, repetitions=1000):
    """Execute circuit on Cirq simulator"""
    simulator = cirq.Simulator()
    result = simulator.run(circuit, repetitions=repetitions)
    
    # Get measurement results
    measurements = result.histogram(key="result")
    return dict(measurements)`;
		} else {
			return `def execute_circuit(circuit, repetitions=1000):
    """Execute circuit on Google Quantum Engine"""
    # Configure engine with your credentials
    engine = cirq_google.Engine(project_id='your-project-id')
    
    # Select a processor
    processor_id = 'rainbow'  # or other available processor
    
    # Run on hardware
    result = engine.run(circuit, repetitions=repetitions, processor_ids=[processor_id])
    
    return dict(result.histogram(key="result"))`;
		}
	}

	private generateTests(ir: QuantumIR): string {
		return `def test_circuit():
    """Validate circuit construction"""
    circuit, qubits = create_quantum_circuit()
    
    # Test 1: Correct number of qubits
    assert len(qubits) == ${ir.hilbertSpace.numQubits}, "Qubit count mismatch"
    
    # Test 2: Circuit has operations
    ops = list(circuit.all_operations())
    assert len(ops) > 0, "Circuit has no operations"
    
    # Test 3: Circuit is valid
    # Unitarity validation for non-measurement circuits
    if not any(isinstance(op.gate, cirq.MeasurementGate) for op in circuit.all_operations()):
        print("\n🔍 Validating Unitarity...")
        try:
            import numpy as np
            # Compute unitary matrix
            U = cirq.unitary(circuit)
            
            # Check U†U = I
            identity = np.eye(len(U))
            product = U.conj().T @ U
            unit_error = np.linalg.norm(product - identity)
            
            if unit_error < 1e-10:
                print(f"✅ Circuit is unitary: ||U†U - I|| = {unit_error:.2e}")
            else:
                print(f"❌ Circuit NOT unitary: ||U†U - I|| = {unit_error:.2e}")
                print("   WARNING: Non-unitary evolution detected!")
                return False
        except Exception as e:
            print(f"⚠️  Unitarity check failed: {e}")
    
    # Circuit diagram validation
    try:
        cirq.testing.assert_has_diagram(circuit, '')  # Validates circuit structure
        print("✅ Circuit diagram valid")
    except Exception as e:
        print(f"⚠️  Diagram validation: {e}")
    
    print("✓ All Cirq tests passed")
    return True`;
	}
}
